spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:./data/ecommerce.db
    druid:
      validation-query: SELECT 1

mybatis-plus:
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.ecommerce: DEBUG
